language: go

go:
  - 1.9

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get github.com/mitchellh/gox
  - dep ensure

install:
  - gox -os="linux windows darwin" -arch="386 amd64" -output=dist/{{.Dir}}_{{.OS}}_{{.Arch}}