language: go

go:
  - 1.9

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get github.com/mitchellh/gox
  - go get github.com/mattn/goveralls
  - go get github.com/onsi/ginkgo/ginkgo
  - dep ensure

script:
  - ginkgo commands --failOnPending --cover --trace -coverpkg=commands
  - gox -os="linux windows darwin" -arch="386 amd64" -output=dist/{{.Dir}}_{{.OS}}_{{.Arch}}
  - goveralls -service=travis-ci

env:
  global:
    - TMPDIR=/tmp